import React, { Component } from 'react';
import Sample1 from '../assets/img/samples/1.png';
import {
    Content,
    ContentHeader,
    ContentBody,
    ContentPrimary,
    ContentPrimaryBody
} from './content';


export default class Home extends Component {

    render() {
        return (
            <Content>
                <ContentHeader toggleSidebar={this.props.toggleSidebar}>
                    Home
                </ContentHeader>
                <ContentBody>
                    <ContentPrimary>
                        <ContentPrimaryBody>
                            <div className="home">
                                    <div>
                                        <h2>Get Started</h2>

                                        <p>To create a new population/generation, click the <b>"New Generation"</b> button in the left hand menu. 
                                            Alternatively, you may import existing data by clicking the <b>"Import button"</b>. This will all you to view
                                            previous data sets or continue where you left off. 
                                        </p>

                                    

                                        <hr/>

                                        <h2>About Imagene Web</h2>

                                        <p>Imagene Web is a rebuild of the existing Imagene C++ application.
                                        The application is an implementation of a genetic programming.</p>

                                        <p>Users create initial populations of math expressions.
                                        From this population, image samples are generated by randomly selecting three individuals of the population to become the inputs for the R, G and B components of each pixel coordinate.</p>

                                        <p>Upon generating samples, users may rank the fitness of each sample. The ranking/fitness assigned is averaged and applied to the underlying individuals for the R, G and B Components.</p>

                                        <p>Once a user is happy with the fitness levels of the current generation/population individuals, they may choose to "evolve" the population into a new generation.</p>

                                        <p>Evolving a population creates a new generation by applying elitism, mutation and crossover to the previous individuals.</p> 

                                        <p><a href="/imagene.pdf" target="_BLANK">You can download a copy of the original paper relating to the c++ application here.</a></p>
                                    </div>

                                    <div className="media" style={{minWidth: 200, maxWidth: 300}}>
                                        <img className="media__image" src={Sample1} alt="Sample" />
                                        <div className="media__caption" >Sample output of Imagene</div>
                                    </div>
                            </div>
                        </ContentPrimaryBody>
                    </ContentPrimary>
                </ContentBody>
            </Content>        
        );
    }
}